version: "3.8"
services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend/data:/app/backend/data
  frontend:
    image: python:3.10-slim
    command: bash -c "pip install streamlit requests && streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    volumes:
      - ..:/workspace
    working_dir: /workspace
